# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Umschlag API" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 8080 8090
VOLUME c:\umschlag

ENV UMSCHLAG_API_DB_DSN boltdb:///umschlag/database.db
ENV UMSCHLAG_API_UPLOAD_DSN file:///umschlag/uploads

ENTRYPOINT ["c:\\umschlag-api.exe"]
CMD ["server"]

COPY bin/umschlag-api.exe c:\umschlag-api.exe
